Repository iNTENSY/api_yamdb, pull requests merged in 2023-11, with the labels that each got.

#6 Feat Permissions
  api_yamdb/api_yamdb/settings.py
Labels: bug / fix

#9 Titles, genres, categories
  api_yamdb/api/models.py
  api_yamdb/api/permissions.py
  api_yamdb/api/serializers.py
  api_yamdb/api/tests.py
  api_yamdb/api/urls.py
  api_yamdb/api/views.py
  api_yamdb/api_yamdb/settings.py
  api_yamdb/reviews/migrations/0001_initial.py
  api_yamdb/reviews/models.py
  api_yamdb/users/migrations/0001_initial.py
  api_yamdb/users/models.py
  requirements.txt
Labels: documentation

#12 Fix auth system
  api_yamdb/api/permissions.py
  api_yamdb/api/serializers.py
  api_yamdb/api/urls.py
  api_yamdb/api/views.py
  api_yamdb/api_yamdb/settings.py
  api_yamdb/users/admin.py
  api_yamdb/users/models.py
  api_yamdb/users/tests.py
  api_yamdb/users/views.py
  requirements.txt
Labels: bug / fix

#13 Feat: review comments
  api_yamdb/api/serializers.py
  api_yamdb/api/urls.py
  api_yamdb/api/views.py
  api_yamdb/reviews/models.py
Labels: feature

#14 Fix: flake8, auth
  api_yamdb/api/serializers.py
  api_yamdb/api/views.py
  api_yamdb/users/models.py
  requirements.txt
Labels: bug / fix

#16 Исправлены баги в titles
  api_yamdb/api/serializers.py
  api_yamdb/api/views.py
  api_yamdb/api_yamdb/settings.py
  api_yamdb/reviews/migrations/0003_alter_title_genre.py
  api_yamdb/reviews/migrations/0004_alter_title_year.py
  api_yamdb/reviews/models.py
Labels: bug / fix
